import { Router } from "express";
import { requireAuth } from "../middleware/auth.js";
import { uploadRateLimiter } from "../middleware/rateLimit.js";
import { uploadEvidence, uploadLogo } from "../controllers/upload.controller.js";
import { evidenceUpload, logoUpload } from "../utils/uploadSecurity.js";
const router = Router();
router.use(requireAuth);
router.post("/evidence", uploadRateLimiter, evidenceUpload.single("file"), uploadEvidence);
router.post("/logo", uploadRateLimiter, logoUpload.single("file"), uploadLogo);
export default router;
